{% set name = "types-toml" %}
{% set version = "0.10.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-toml-{{ version }}.tar.gz
  sha256: b7e7ea572308b1030dc86c3ba825c5210814c2825612ec679eb7814f8dd9295a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/toml-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for toml
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
