{% set name = "types-toml" %}
{% set version = "0.10.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-toml-{{ version }}.tar.gz
  sha256: 6aeb3ed7bfa869381551c774ed6a9142e3eed98a83efa5108a9632eafd56dcd3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/toml-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for toml
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
